"use client";

export type EditableSvgVectorizeOptions = {
    maxEdge?: number;
    colorStep?: number;
    alphaThreshold?: number;
    title?: string;
};

export type EditableSvgVectorizeResult = {
    svg: string;
    width: number;
    height: number;
    sampledWidth: number;
    sampledHeight: number;
};

const DEFAULT_MAX_EDGE = 96;
const DEFAULT_COLOR_STEP = 32;
const DEFAULT_ALPHA_THRESHOLD = 10;

export async function rasterImageToEditableSvg(source: string, options: EditableSvgVectorizeOptions = {}): Promise<EditableSvgVectorizeResult> {
    const image = await loadImage(source);
    const width = Math.max(1, image.naturalWidth || image.width || 1);
    const height = Math.max(1, image.naturalHeight || image.height || 1);
    const maxEdge = Math.max(16, Math.min(180, Math.floor(options.maxEdge || DEFAULT_MAX_EDGE)));
    const scale = Math.min(1, maxEdge / Math.max(width, height));
    const sampledWidth = Math.max(1, Math.round(width * scale));
    const sampledHeight = Math.max(1, Math.round(height * scale));
    const colorStep = Math.max(1, Math.min(128, Math.floor(options.colorStep || DEFAULT_COLOR_STEP)));
    const alphaThreshold = Math.max(0, Math.min(255, Math.floor(options.alphaThreshold ?? DEFAULT_ALPHA_THRESHOLD)));

    const canvas = document.createElement("canvas");
    canvas.width = sampledWidth;
    canvas.height = sampledHeight;
    const context = canvas.getContext("2d", { willReadFrequently: true });
    if (!context) throw new Error("当前浏览器不支持图片转 SVG");
    context.imageSmoothingEnabled = true;
    context.imageSmoothingQuality = "high";
    context.clearRect(0, 0, sampledWidth, sampledHeight);
    context.drawImage(image, 0, 0, sampledWidth, sampledHeight);

    const pixels = context.getImageData(0, 0, sampledWidth, sampledHeight).data;
    const rects: string[] = [];
    for (let y = 0; y < sampledHeight; y += 1) {
        let x = 0;
        while (x < sampledWidth) {
            const color = quantizedPixel(pixels, sampledWidth, x, y, colorStep, alphaThreshold);
            const startX = x;
            x += 1;
            while (x < sampledWidth && quantizedPixel(pixels, sampledWidth, x, y, colorStep, alphaThreshold) === color) x += 1;
            if (color !== "none") rects.push(`<rect x="${startX}" y="${y}" width="${x - startX}" height="1" fill="${color}" />`);
        }
    }

    const title = escapeXml(options.title || "Editable image");
    const svg = [
        `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${sampledWidth} ${sampledHeight}" role="img" aria-label="${title}">`,
        `<title>${title}</title>`,
        `<desc>Generated by Imge Worker editable conversion. Each colored rectangle can be edited in an SVG editor.</desc>`,
        `<g id="editable-raster" shape-rendering="crispEdges">`,
        ...rects,
        `</g>`,
        `</svg>`,
    ].join("\n");

    return { svg, width, height, sampledWidth, sampledHeight };
}

export function svgToDataUrl(svg: string) {
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

export function svgToBlob(svg: string) {
    return new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
}

export function dataUrlToSvgText(dataUrl: string) {
    const match = dataUrl.match(/^data:image\/svg\+xml(?:;charset=[^;,]+)?(;base64)?,(.*)$/i);
    if (!match) return "";
    if (match[1]) {
        const binary = atob(match[2] || "");
        const bytes = new Uint8Array(binary.length);
        for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
        return new TextDecoder().decode(bytes);
    }
    return decodeURIComponent(match[2] || "");
}

export function sanitizeEditableSvg(svg: string) {
    const parser = new DOMParser();
    const document = parser.parseFromString(svg, "image/svg+xml");
    if (document.querySelector("parsererror")) throw new Error("SVG 格式不正确，请检查标签是否闭合");
    const root = document.documentElement;
    if (!root || root.tagName.toLowerCase() !== "svg") throw new Error("请输入完整的 <svg> 内容");

    document.querySelectorAll("script,foreignObject,iframe,object,embed,link,meta").forEach((element) => element.remove());
    document.querySelectorAll("*").forEach((element) => {
        for (const attribute of Array.from(element.attributes)) {
            const name = attribute.name.toLowerCase();
            const value = attribute.value.trim().toLowerCase();
            if (name.startsWith("on") || value.startsWith("javascript:")) element.removeAttribute(attribute.name);
        }
    });
    root.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    return new XMLSerializer().serializeToString(root);
}

function quantizedPixel(pixels: Uint8ClampedArray, width: number, x: number, y: number, colorStep: number, alphaThreshold: number) {
    const offset = (y * width + x) * 4;
    const alpha = pixels[offset + 3];
    if (alpha <= alphaThreshold) return "none";
    const red = quantizeChannel(pixels[offset], colorStep);
    const green = quantizeChannel(pixels[offset + 1], colorStep);
    const blue = quantizeChannel(pixels[offset + 2], colorStep);
    if (alpha < 250) return `rgba(${red},${green},${blue},${(alpha / 255).toFixed(3)})`;
    return `#${hex(red)}${hex(green)}${hex(blue)}`;
}

function quantizeChannel(value: number, step: number) {
    return Math.max(0, Math.min(255, Math.round(value / step) * step));
}

function hex(value: number) {
    return value.toString(16).padStart(2, "0");
}

function escapeXml(value: string) {
    return value.replace(/[<>&"']/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" })[char] || char);
}

function loadImage(source: string) {
    return new Promise<HTMLImageElement>((resolve, reject) => {
        const image = new Image();
        image.onload = () => resolve(image);
        image.onerror = () => reject(new Error("图片读取失败，无法转成可编辑 SVG"));
        image.src = source;
    });
}
